### ISSUE TITLE
Book talks for Event 2 (January 2016)

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#10]
Jo Hinchliffe as kindly said he will talk about "20 minutes of random stuff" for us in January.

**Comment by carwyn** [comment]
If he's available Graham Worley will also be talking about a project he did for the Cayman Islands.

**Comment by carwyn** [comment]
Graham has confirmed for the 27th and OpenEnergy Monitor are also willing.

**Comment by carwyn** [comment]
So far:

* Paul Harding: Coffee Incident Management (see FB group) (15 mins)
* Jo Hinchliffe : My DIY Space (15 mins)
* Carwyn: OWASP Zap and Mitmproxy, debugging and securing web applications (15 mins)
* Sim Walker: Advanced Tech Fuel (Tea and Coffee) (5 mins)
* Carwyn: A Day Trip to Slough Trading Estate (5 mins)

**Comment by davehun** [comment]
happy to do some docker at some point  ...

**Comment by robshep** [comment]
February/March please Dave, I'm away in Jan! :)


Rob Shepherd BEng PhD
07596154845
rs@datacymru.net

**Comment by carwyn** [comment]
Chris J. Headleand is interested in giving a talk about AI and/or Games

**Comment by carwyn** [comment]
From meetup:

David Goadby:
> I already have some ESP8266 and have just started to use them so I too would be interested in NodeMCU/ESP8266. I'm ok on Arduino and Rpi but, if you can find a Kivy expert I would pay to listen to them!

PJ:
> If you are looking for possible subjects for Short Talks could you consider NodeMCU/ESP8266

**Comment by carwyn** [comment]
Jo Mearman has a drone we might be able to use, may be able to give a talk too.

**Comment by carwyn** [comment]
We went with Chirs Headleand, Graham Worley and Jo Hinchliffe.
