### ISSUE TITLE
Venue and Refreshments for Event 2 (January 2016)

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#12]
We have somewhere in mind for this and will confirm during the week of 14th Dec

**Comment by peejpeejpeej** [comment]
Due to a number of factors I wont be able to attend all of the 2016 meetings. With this in mind is there someway you could advance us a copy of **possibilities** and their dates so I can move things around earlier or is this an impossibility? *Thanx chaps.*

**Comment by carwyn** [comment]
We'll try and give more notice of dates and rough locations. The most forward thinking info will always be in the Github issues, the milestones pages in particular is useful:

https://github.com/NorthWalesTech/NorthWalesTech/milestones

**Comment by carwyn** [comment]
Venue will be either the CoLearn or CoLab areas in Pontio. Pontio have said they will sponsor refreshments if needed although I'll speak to SuperTemps to see what they'd like to do too.

**Comment by carwyn** [comment]
Used coLAB in Pontio for refreshments and PL2 in Pontio for the talks. Very good venues.
