### ISSUE TITLE
Book talks for Event 3 (March 2016)

### ISSUE THREAD

**Issue by robshep** [NorthWalesTech/NorthWalesTech#14]
Aaron Owen: https://uk.linkedin.com/in/aaron-owen-167184103

... works for D&H on Parc Menai and expressed an interest in doing a talk on HPC at NWT.

This ticket can be used to discuss the idea and link it to the event schedule! 
(currently set at event 3)

**Comment by carwyn** [comment]
HPC Wales may be able to say something about HPC too. They are in the final stages of finding out if they get funding for Mk2.

**Comment by carwyn** [comment]
February 29th (Monday) would be cool for this given @robshep called the event "The Magic Number".

**Comment by carwyn** [comment]
@davehun wants to do one on Docker, I can add OpenShift 3 to this mix. It would be good to mention Kitematic in this conversation too. @robshep wants to see this though but he's away in Jan.

**Comment by carwyn** [comment]
@robshep has been asked to do his Java 8 one so this event seems to make sense as he's back. This along with Docker and HPC would seem to make for a more in depth event. I'll volunteer to do an "Anything but Java" talk on languages for the JVM that are not Java (Clojure, Scala, Groovy etc.)

**Comment by carwyn** [comment]
Surely some one needs to do one on https://en.wikipedia.org/wiki/Magic_number_(programming)

**Comment by carwyn** [comment]
@davehun a series on Docker, Kitematic, CoreOS/Atomic and OpenShift 3 and their relationship to development and deployment environments would fit well.

**Comment by carwyn** [comment]
Latest working list:

First Half: Random Stuff 

* Pro Photos - Focus, There is Moire (Ben Walker) 20 mins 
* From Containers to Self-Contained (Carwyn) 20 mins 
* A Very Special Launch (Jo Hinchliffe and John Story) 5 mins

Refreshment Break

* Sponsored by Supertemps (20 mins)

Second Half: Developer Stuff

* Vagrant Built Virtual Machines (Sim Walker) 20 mins 
* How We Use Docker (David Hunnisett) 20 mins 
* Java 8: The Interesting Bits (Rob Shepherd) 20 mins 

Backup Talks

* Hackers: Know Your Enemy  (Carwyn) 20 mins

**Comment by carwyn** [comment]
One more on the list:

* Droning On: Quadcopters! (Joe Mearman) 20 mins

**Comment by carwyn** [comment]
Going to split this as mentioned previously, mainly to get the Ty Menai after work coverage to see if we can recruit numbers. The other talks can move to late April or early May noting that TEDx is April 1st.

This is a more developer focussed event based in Ty Menai catering to requests for coverage of certain topics.

Schedule:
17:45 to 18:00 After Work Refreshments 
18:00 North Wales Tech Update (Carwyn) (5 Mins)

Developer Talks 18:05 to 19:35
* Java 8: The Interesting Bits (Rob Shepherd) 20 mins
* Vagrant Built Virtual Machines (Sim Walker) 20 mins
Mini Break Featuring Supertemps Update (10 mins)
* How We Use Docker (David Hunnisett) 20 mins
* From Containers to Self-Contained (Carwyn) 20 mins

**Comment by carwyn** [comment]
Split off the unused talks [here](wiki/Prospective-Talks).
