### ISSUE TITLE
Book venue and refreshments for Conwy Event

### ISSUE THREAD

**Issue by robshep** [NorthWalesTech/NorthWalesTech#29]
Conwy Business Centre have proposed Thursday May 19th. 

Any objections?

**Comment by davehun** [comment]
Could we not get may the 4th

**Comment by carwyn** [comment]
The main thing is getting speakers that can commit to the date.

**Comment by robshep** [comment]
Conwy business center only have this date or the 12th available for us.

There seems to be some mentions of an event in late April??

So, I think May 19th will give us plenty of time to organise everything and also keep events far enough apart.

I'll try and have speakers confirmed by end of April, so we've got enough time thence to cancel should we need to.

Any major objections?

Rob

**Comment by carwyn** [comment]
The end of April event spring up as Jo's managed to convince a hackspacer that's over from California for a residancy at Madlab in Manchester during April to come over to give a talk and workshop. Also got someone to talk about microbit and teaching kids.

**Comment by robshep** [comment]
Great, so end of May fine with you for Trip to Conwy?

**Comment by carwyn** [comment]
Absolutely, happy to do the about us talk, by then I'm hoping to re-spin it as a Creative Commons reveal.js thing with no copyright issues for anyone to re-use.

**Comment by carwyn** [comment]
Doubt I'll be able to commit to much else until nearer the time though as I have Veillance (art thing) and Gregynnog to prep for. Happy to help arrange things though if needed. Gary Smith is a key contact over that way. Prodding Coleg Llandrillo is also on the todo list. Cambrian Photography (Colwyn Bay) are usually very supportive too and have shown an initial interest.

**Comment by carwyn** [comment]
Sian's contacts in the Conwy area would be invaluable for canvasing and attracting interest too.

**Comment by robshep** [comment]
No problem.  Sian will be helping to do a press release soon for the local papers. and will be canvassing local business.  Sian's sister is PA to the principle of llandrillo/menai college, a good contact there too.

**Comment by robshep** [comment]
Booked.  19th May

**Comment by jonbullock** [comment]
If you need a hand with anything on the day just let me know, as I'll be on Conwy all day.

**Comment by carwyn** [comment]
@robshep what time do we have the venue until on the 19th?

**Comment by carwyn** [comment]
Supertemps stepped in again. Many thanks for this!
