### ISSUE TITLE
hackaday event?

### ISSUE THREAD

**Issue by davehun** [NorthWalesTech/NorthWalesTech#30]
@carwyn could we get pontio fablab ?
https://docs.google.com/a/elidirhealth.co.uk/forms/d/11wuH0N-3kXs83H99PeiLsjM-bD5Kv1IuoBGGJLvhySc/viewform?c=0&w=1

**Comment by carwyn** [comment]
We can ask, the fablab and colab have difference H&S rules, colab is a lot easlier as there's no tools in there.

**Comment by davehun** [comment]
past
