### ISSUE TITLE
Tech Talks for Conwy event.

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#31]
List of possible speakers:

Carwyn: Intro Mk 3
Rob: His fault, he can talk about something :)
Ian Woodrow maybe (based in Abergele): Wind turbine software.
Cambrian Photography have shown an initial interest.
Gary Smith: keen as he's Llandudno based.
Ronan: Techy art.
Ant Dickinson: music tech
Conwy Council as sponsors?

.. there are more in my head :)

**Comment by jonbullock** [comment]
If I'm about that week I'd be happy to do a talk on JBake.org

**Comment by carwyn** [comment]
Ant has confirmed he'd like to do one in Conwy. He's also keen to do a larger Art and Tech one later in the year.

**Comment by robshep** [comment]
Les Pritchard of Neterix (tech talk & presentation)

**Comment by robshep** [comment]
Possibly Jon Leighton of Loco2 ( needs some coercion :) )

**Comment by carwyn** [comment]
Ian Woodrow needs time to get permission from previous employer. The energy focused event in Electric Mountain may be a better target.

**Comment by carwyn** [comment]
Have we got an initial list we can put up on meetup?

- Jon (JBake)
- Ant (Pure Audio and Performance) (I think)
- Les (Something security related).

Cameron Gray has a networking related one he's mentioned too.

**Comment by carwyn** [comment]
If you need me to MC for this I can, thinking Medieval & Castles undertones.

**Comment by robshep** [comment]
**Confirmed** as of 11/5

Jon Bullock - JBake and ASCIIDoctor
Les Pritchard - Title TBC
Jonny Coombes - Experiences and Primer of Scala
Ant - Pure Data Audio and Performance
Supertemps - IT recruitment sponsored refreshments break

I'll put together a 5min primer on the NodeMCU boards as a way of generating interest in future hacking projects.

Waiting on replies from invited speakers: CP, JL & CG, i'll update shortly.

R

**Comment by carwyn** [comment]
@robshep yy Adafruit Huzzah esp8266 (NodeMCU and Micropython compatiible) arrived yesterday. Fancy doing a double act intro to esp8266? Triple act if @davehun is interested?

Would be good to have some flashy lights there!

Really keen to start running micro-controller workshops in June/July.

**Comment by robshep** [comment]
Surething.  I just had arrive a Weemo LUA board.


I’m not sure how much time I’ll have for tinkering, but should be fun.

I think the approach of one person making slides and the other person delivery the presentation was humorous and could be developed further?!?.

I notice JSOxford have a “show and tell” - I’d like to introduce this as a means of getting more engageemnt and interaction - I think there's lots of possibility and something I really enjoyed at the december event.

I'm happy to do a show and tell on the Weemo, if you want to do one on the Huzzah, maybe @glynhudson has used the esp8266 also!

We could advertise a show and tell session to prep the delegates and then fill in with our own?

**Comment by carwyn** [comment]
How about I make a deck for ESP8266 related stuff (high level) and we do what Jo and I did at the last event? :) All he send me was a few photos he definitely wanted in and I .. erm .. took liberties.

I can talk about Micropython if @robshep or @davehun can talk about NodeMCU .. both run on the ESP8266.

Show and Tell 2-5 min talks came up with Jo too, as did "slide roulette" where people do talks about each other's slides. Tamsin was particularly interested in smaller events where people can dip their toes in public speaking, thinking PAYF Cafe or Lodge Dinorwig or Caban for this.

An "everyone must talk" event focusing on how to give talks was also mentioned. There are a few random slideshow generators out there too that build decks from search queries :)

This book is very much worth reading too: https://www.amazon.co.uk/Confessions-Public-Speaker-Scott-Berkun/dp/1449301959

**Comment by carwyn** [comment]
An ESP intro is worth doing in Gwynedd too as it will help round people up to do hands on stuff which after the Soldering Workshop feedback (very positive) I'm really keen to do.

**Comment by robshep** [comment]
Only if you refrain from calling it a "deck" - corporate buzzword bingo terms make me shudder. 

The more people who start using the term "deck" makes me want to revert back to Clear OHP slides and pens!! 

We could feature that in a "retro" tech event HA HA.  (no joke)

Yes, more on ESP certainly as we go forward, but I was going to do just two slides.  one for hardware, and one for a LUA HTTP client on a pin event etc.... as a quick appetite whetter

**Comment by jonbullock** [comment]
My talk will just be on JBake for now, I'll leave Asciidoctor for another talk at a different event.

**Comment by carwyn** [comment]
@robshep ha ok, that's given me an idea :) "deck" is banned.

We so need to do a buzzword bingo social event.

Will see what I have time to rustle up.

**Comment by carwyn** [comment]
Ant's title: Crossed Lines' - the trials and tribulations of making digitally controlled medieval Welsh musical instruments (integrating Pure Data with solenoids on musical instruments).

**Comment by robshep** [comment]
_Update_
**Confirmed** as of 11/5 13:00

• Jon Bullock - JBake, static site generation

• Jonny Coombes - Experiences with Scala

• Les Pritchard - A surprise. 

• Jon Leighton - High and Lows of OpenSource: A perspective from a Rails core developer.

• Ant Dickinson - Crossed Lines' - the trials and tribulations of making digitally controlled medieval Welsh musical instruments (integrating Pure Data with solenoids on musical instruments).

• Show and Tell - Stand up and tell us your tech! Quick fire: including an introduction to ESP8266 and NodeMCU/Micropython

• Supertemps: IT recruitment sponsored refreshments break.

That's a great line up, enough for the invite to out again!

R

**Comment by robshep** [comment]
emailed out via meetup group

**Comment by carwyn** [comment]
@robshep are you ok with a 7pm start for the actual talks? Mentioned in email to yourself and Sian about the other event in Bangor that's finishing at 18:30:

http://www.goodpractice.wales/bangor-day-9-the-use-of-technology-in-the-pursuit-of-behaviour-change

**Comment by robshep** [comment]
@carwyn Yep - that's what I'm aiming for!

**Comment by carwyn** [comment]
I can offer lifts over from Bangor (typically people at the above event) to Conwy.

**Comment by robshep** [comment]
Les will be talking on Rancher (A docker platform) which is a continuation of a theme and leads into advertising the Docker workshop.

**Comment by carwyn** [comment]
@davehun we need details for the Docker workshop (date and location by the 19th. I'm scoping out locations on Friday.

**Comment by glynhudson** [comment]
@davehun @carwyn 👍 for docker workshop. Keen to get an Emoncms docker image working. Just setup our new community forums based on discourse using a pre-built docker image. So nice and easy https://community.openenergymonitor.org/.....although I didn't have the build the dokcer image myself!

**Comment by carwyn** [comment]
Docker ticket is #34

**Comment by carwyn** [comment]
Microcontroller workshop series in #45
