### ISSUE TITLE
Docker Workshop Technical Details

### ISSUE THREAD

**Issue by davehun** [NorthWalesTech/NorthWalesTech#34]
I have some matterial for docker for a docker workshop.
How about a date ~ 16th of june to co incide with dockercon?

**Comment by davehun** [comment]
Need a location with good public wifi.

**Comment by glynhudson** [comment]
> Need a location with good public wifi.

Surprisingly hard to find! We could use large meeting room in Intec a few doors down from my office. Could share our very fast WiFi. I will find out the cost

**Comment by davehun** [comment]
whats it like for out of hours ?

**Comment by glynhudson** [comment]
Cost of using the big Intec meeting room is £23 for me and we can use it
after hours if I take responsibility for you hooligans :-)

On 11 May 2016 at 16:55, David Hunninsett <notifications@github.com> wrote:

> whats it like for out of hours ?
> > On 11 May 2016, at 16:51, Glyn Hudson <notifications@github.com> wrote:
> >
> > Need a location with good public wifi.
> >
> > Surprisingly hard to find! We could use large meeting room in Intec a
> few doors down from my office. Could share our very fast WiFi. I will find
> out the cost
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub <
> https://github.com/NorthWalesTech/NorthWalesTech/issues/34#issuecomment-218502463
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/NorthWalesTech/NorthWalesTech/issues/34#issuecomment-218503770>
>



-- 
Glyn Hudson

http://megni.co.uk
http://adventuresplusnorthwales.blogspot.com

**Comment by robshep** [comment]
I'm sure we can get Intec for free as Gwynedd Council own it and they are keen to support us.  
Ty menai is also suitable. 

16th is a Thursday, and i'm not sure what the take up will be midweek.  Better on a Saturday?

Either way it's only a month away and we should advertise it on Thursday evening.

**Comment by carwyn** [comment]
We're aiming for 19th to 21st in line with DockerCon. Twitter poll favoured Monday, Facebook Sunday and Tuesday. CoWork in Pontio is available, need to test the "TheCloud" wifi for suitability. Temporary accounts may be possible for small numbers should TheCloud not work.

Can someone comment on Ty Menai and Intec wifi and internet capabilities?

This must have either bomb-proof wifi with good back-haul internet or a local docker image cache which we pre-seed. It needs to handle concurrent downloads of hundreds of MB. Poll figures suggest numbers of up to a dozen. Even this many can push a low grade WiFi access point and would need at least FTTC bandwidth minimum. 

Has anyone done a timed run through the material?

**Comment by glynhudson** [comment]
If we used the room in Intec we can use my office WiFi which is plugged
into Intec's network which is direct into Fibre Speed network. We easily
get 30/40Mbps up/down during the day (probably more in the evening). It's
not a problem for us to cover the (token) £23 charge.

16th, 19th or 21st would be good with me.

On 16 May 2016 at 12:35, Carwyn Edwards <notifications@github.com> wrote:

> We're aiming for 19th to 21st in line with DockerCon. Twitter poll
> favoured Monday, Facebook Sunday and Tuesday. CoWork in Pontio is
> available, need to test the "TheCloud" wifi for suitability. Temporary
> accounts may be possible for small numbers should TheCloud not work.
>
> Can someone comment on Ty Menai and Intec wifi and internet capabilities?
>
> This must have either bomb-proof wifi with good back-haul internet or a
> local docker image cache which we pre-seed. It needs to handle concurrent
> downloads of hundreds of MB. Poll figures suggest numbers of up to a dozen.
> Even this many can push a low grade WiFi access point and would need at
> least FTTC bandwidth minimum.
>
> Has anyone done a timed run through the material?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/NorthWalesTech/NorthWalesTech/issues/34#issuecomment-219405458>
>



-- 
Glyn Hudson

http://megni.co.uk
http://adventuresplusnorthwales.blogspot.com

**Comment by carwyn** [comment]
We've not been to Intec yet and as @robshep says it would be good to call on Gwynedd Council's offer.

Announcing a date would be enough on Thursday, I'd prefer the 19th or 21st as they align with DockerCon, we can put up stuff from their event at ours that way.

@glynhudson is there any difference between Sunday afternoon and Tuesday evening from an Intec perspective?

**Comment by carwyn** [comment]
@davehun what's the situation with Ty Menai Wifi and internet?

Note that we'd have to buy food on the Sunday or drinks on the Tuesday to get the room for free.

**Comment by davehun** [comment]
internet is stable an lots of AP not desperately fast but very solid. Might be faster out of hours.

**Comment by carwyn** [comment]
@davehun PSK or batch of user accounts?

**Comment by davehun** [comment]
?

**Comment by carwyn** [comment]
Single Pre Shared Key (PSK) or WPA2 Enterprise (per user account)

**Comment by davehun** [comment]
PSK

**Comment by davehun** [comment]
i assume you mean Ty Menai

**Comment by robshep** [comment]
Re: Ty Menai if it is a contender:  we also have the option of running long Ethernet cables from a meeting room cabinet (assuming one of the rooms in software hotel wing) which will provide significantly better throughput. 

I used to do this for anyone one mentioned booking keywords such as "youtube, live demo, skype etc" 

I used to just run a huge heap of 20 meter cables, and arrange the desks along a wall/divider if possible.  Worked great.  Easily fast enough.

Like all shared office environments, during the day the wifi is congested due to the number of APs all self-managing on a very selected number of 802.11 channels. 

I think Lee is still doing network technician duties there so I can just tell him what to do

**Comment by glynhudson** [comment]
>  is there any difference between Sunday afternoon and Tuesday evening from an Intec perspective?

Just sent an email to ask the fascility manger John Johns. Should have a answer tomorrow. Should be fine.

**Comment by davehun** [comment]
No self managed Aps any more (in theory)

**Comment by glynhudson** [comment]
Meeting rooms in Intec are week days only. I can't use them at the weekend
apparently..

- sent from my mobile device

**Comment by carwyn** [comment]
We need to be sure of both of these things:

1. Are we allowed to connect our own access points to the Ty Menai cabinets.
2. If not is the public Wifi present and usable? 

We need to test this before the evening with enough time to change venue if it doesn't work. On more than one occasion I've seen adding kit to a network nuke it completely: IP clashes, rogue DHCP, rogue RIP, Cisco VTP takover. In the latter case every switch on the host network had to be rebooted. Some of the commercial kit will also signal jam rogue APs to make them unusable.

I tested "The Cloud" on a laptop in Pontio and can get consistent 2Mbit with no interruptions as long as you stay in one place and keep your laptop on. Any disconnection will often force you back to the captive portal. The main issue is that throughput at 2Mbit is only 100KBps, this is throttled at the Wifi controller level.

Once fabFriday members have logins they will have 20Mbps WPA2 Enterprise which actually works :) At least concurrency isn't an issue there. Most consumer grade kit conks out pretty quickly with more than a handful of heavy users, either CPU limited or things like dnsmasq default config limited to very small default address pool size.

I'm probably being paranoid I know but we have people driving over from Prestatyn and Chester for it already :)

I'll see if I can book CoWork as a plan B on Tuesday. I have a "yes" in principle. I think Ty Menai is a better location if we can make sure it works though.

**Comment by carwyn** [comment]
From @robshep 

The capacity of the current room (rm 102) varies by layout but 20-30 will be fine. But we can move to 105 where we were last time if needed. 

I've requested a call with aytel, the IT provider, who should be calling me back to confirm details. I gave them loads of assistance setting up when they were handed the contract so they'll be helpful. There's feck all AUP or SLA but the raw wired connection will be fast enough after hours. 

I'll sort a spare switch and a bunch of cables from the comms room so we can get everyone hooked up.

There certainly was no access control when I provided network access to the guest/event network as it was too much hassle. I'm going to double check that this hasn't changed and test it out in the next week or so.

My opinion is that limiting numbers to 20 + experts/organisers will make for a better event than having a larger number of participants all requiring assistance and bandwidth.

Q for @davehun  Apparently we can run a registry as a pass-thru proxy? So if all the participants are going to be requesting the same images for the tutorial then that could be pre-seeded during the day?

**Comment by carwyn** [comment]
If we are going wired we'll need to remind people to bring their ethernet dongles.

Agreed with numbers, we can always run more workshops. To be honest a regular series would be quite cool.

I was thinking about the local registry/proxy idea too, a "Docker Workshop" in a box :)

**Comment by carwyn** [comment]
@davehun @robshep the Docker Workshop is now full with more people asking about places.

The biggest challenge I'm expecting is getting people up and running on docker, especially given the range of OSes involved. Virtualbox on Windows is a particular pain point, especially if they have HyperV or VMware installed. The state some people get OS X into may also cause problems. The main issues I've hit are left over cruft from previous hypervisor installs, usually network stuff.

Latest linux distros don't even need the toolbox installed, new enough versions are already in the package repos. These are probably preferable to adding extra apt/yum sources as they can cause issues with future distro upgrades.

**Comment by jonbullock** [comment]
For what it's worth I signed up for access to the Private Beta last week and I've already received my token to download it.

**Comment by carwyn** [comment]
@jonbullock I jumped ship to the beta as soon as I could too. Docker on HyperV is far more reliable than Virtualbox on Win 10 Preview (the other platform I have to work with :( ) but I'd not recommend it for RTM versions of Windows as it really is beta. On OS X is depends how well baked xhyve is?

**Comment by jonbullock** [comment]
I never got as far as to actually install Toolbox on OS X and reading the comments I'm kinda glad I didn't. Does it matter for the workshop which version we go for?

**Comment by carwyn** [comment]
@jonbullock I've not tried Docker on OS X @davehun ?

**Comment by davehun** [comment]
The toolbox for me was fine apart from one occasion where a bug in my own virtual box install caused a day of pain.
The beta has been ok for me one small bug where it consumed all my disk space.
Defiantly not had any of the problems Carwyn is describing on windows.

**Comment by carwyn** [comment]
@davehun  "one small bug where it consumed all my disk space" is not a small bug. This is what I mean by beta.

**Comment by carwyn** [comment]
@davehun and "a bug in my own virtual box install caused a day of pain." is similar to what I had on Windows. Have you tried the xhyve version in anger yet?

**Comment by davehun** [comment]
yes  its great so far. Switching was a pain and the disk eating bug was annoying but back to normal now.

**Comment by robshep** [comment]
1. FWIW, I had an existing VirtualBox install and installed docker toolbox the other day and it all "just works"

2a. I was contemplating that maybe there is a "live CD" linux image that will work for the purposes of the workshop as a fallback. (not looked into which one)

2b. If docker toolbox happens to be borked - will just running boot2docker in an existing working virtualisation envrionment be suitable?

**Comment by carwyn** [comment]
@robshep 2b: Yup Running any standard linux distro in any HyperVisor would be a good fallback. This avoids host to guest shared filesystem issues too. I'm hoping that most of the issues I've seen won't exist on most people's machines as they were mostly early Windows 10 and VirtualBox 5 problems. The toolbox in general has grown up a lot in the last few months.

I'm going to run through the full tutorial on Ubuntu and Windows 10 in the next week or so to see where it's at, not used Ubuntu in ages so will be good to see.
