### ISSUE TITLE
Pontio Web Site UX Issues

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#51]
Quite a number of people have reported issues with the https://www.pontio.co.uk/ site. This is a ticket to collate these from the unique perspective of NWTech. A lot of us are professional web design experts.

**Comment by carwyn** [comment]
Many of the UI elements do not use responsive design meaning that the widgets and often text are tiny when interacting with the site on a mobile device. Given the market dominance of mobile devices this is a big issue. The Pontio App doesn't solve this as it's largely an embedded web view of the main site so has the same problems.

**Comment by carwyn** [comment]
For events that have prerequisites (i.e. you can only see them if you are logged in) it's non obvious how a user initially logs in. The workaround is to click "My Account" and log in there, then go back to looking for the event.

**Comment by carwyn** [comment]
You can't click on an event picture or text in the events listings to see the event specific page, only the "View" button works.

**Comment by carwyn** [comment]
If you navigate to an event all event specific pages have the same URL:

https://www.pontio.co.uk/Online/default.asp

This is **very** bad design as it's impossible to share an event by copying the URL or using browser plugins designed to share pages. You can't bookmark event pages either.

**Comment by carwyn** [comment]
There are no social media "share this event" widgets on any of the event pages.

**Comment by carwyn** [comment]
At least one user has reported not receiving password reset information by email.

**Comment by carwyn** [comment]
@lukepfarrar @davehun can you add what you've found.

**Comment by carwyn** [comment]
When trying to book a seat for a theatre performance the seat selection widget makes the individual seats tiny meaning the user has to zoom in to select one. However once a seat is "clicked" nothing appears to happen. What really happens is that a ticket type selector dialogue (student/child/adult) pops up in the areas off-screen. I've tested this and for a zoom level that allows a seat to reliably be selected (fingers and thumbs remember) the dialgue pretty much always ends up off screen.

**Comment by tomusher** [comment]
'Availability' icons on event pages are not colour blind friendly.

**Comment by davehun** [comment]
The postcode / address lookup widget requires a very specific flow. It broke a few times when I registered so I now have 2 accounts.
I recently tred to change my address. This broke 3 times before I was able to change it successfully (again the postcode address lookup widget)

**Comment by tomusher** [comment]
Awkward redirect and generally non-functional with Javascript disabled

**Comment by Tsany** [comment]
> There are no social media "share this event" widgets on any of the event pages.

This isn't *such* a big problem, however, at the very least, I would like to be able to copy the URL for any page, send it to someone and for them to actually see the page instead of the language choice page.  

Speaking of which:
- It should remember my language choice across sessions.

**Comment by tomusher** [comment]
Numerous navigation elements with no alt text or clear alternative navigation route:

- What's on today
- Subscribe to Pontio Updates
- View our brochure
- View our cinema e-brochure

**Comment by Tsany** [comment]
The position of "My account" in the main menu bar is kind of unintuitive.  Generally, we find login/user details and setting somewhere along the very top of the page. (a la FB, twitter, amazon, every other website)  

If that's where users are looking for this feature, let's not throw them off.

**Comment by carwyn** [comment]
These have been passed on. Something may or may not come from it.
