### ISSUE TITLE
CodeJam: Go 1.8 Release Party

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#57]
A few people have shown an interest in learning more about the [Go Programming Language](https://golang.org/) and a few others are already using it. This CodeJam will introduce Go (aka Golang) with some hands on time along with a few short talks about how some of us are using it, how the language and environment works, and some examples of prominent software already written using it.

This event is scheduled to coincide with the [Go 1.8 Release Party](https://github.com/golang/go/wiki/Go-1.8-Release-Party) events planned for the version 1.8 release in February.

**Comment by carwyn** [comment]
Meetup event for this is here https://www.meetup.com/NorthWalesTech/events/236961582/

**Comment by carwyn** [comment]
Things I think would be worth covering:

* General intro and motivation.
* What's not in it.
* Environment and tooling.
* Packaging and static compilation.
* Type system, double dispatch, interfaces.
* Concurrency via Goroutines.
* Channels.
* Popular projects using it in anger (Docker, Kubernetes, Hugo, Caddy, Syncthing, InfluxDB, Prometheus)

**Comment by carwyn** [comment]
Things to remember:

* Not everyone will have used a compiler.
* The main function and its relation to package definitions.
* Some may well turn up with Windows.
* GOPATH
* Many will not have used pointers.
* There's a lot to cover just in the basics of the language in terms of types, interfaces, 
* The [Book](https://www.amazon.co.uk/Programming-Language-Addison-Wesley-Professional-Computing/dp/0134190440)
* Project layout for commands, libraries and combinations (there is a convention here).

**Comment by carwyn** [comment]
Have you got a set of slides for the intro? I don't helping with some of the intro as I'll need to introduce you lot anyway :)

**Comment by carwyn** [comment]
Creative Commons licences pictures here: https://golang.org/doc/gopher/

**Comment by carwyn** [comment]
A reason to use 1.8 for new users the new default GOPATH!

**Comment by lukepfarrar** [comment]
Slide tool: https://godoc.org/golang.org/x/tools/cmd/present
