### ISSUE TITLE
Book venue for Event 1 (December 2015)

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#6]
Options so far: MALT in Bangor Uni Main arts.
Dean St big lecture theatre?

**Comment by carwyn** [comment]
After 6pm all University large room bookings go via http://www.bangor.ac.uk/conference_office/ MALT is almost certainly the best option for December as security cover is easy (they are already in the building). Dean St needs special arrangements for evening events. Both have refreshment areas.

In the future (hopefully January) Pontio will have suitable rooms available.

**Comment by robshep** [comment]
@carwyn did you call Pontio today?

**Comment by carwyn** [comment]
Yup, need to speak to someone tomorrow again to find out about Pontio specifically otherwise we can go for one of the other non Pontio rooms.

**Comment by carwyn** [comment]
Pontio is out for Event 1, maybe for Event 2. To give you an idea of the sheer choice of rooms available at the Uni:

http://www.bangor.ac.uk/itservices/av/lecturerooms/roomslist.php?depid=1

**Comment by carwyn** [comment]
Dean St S-6: Flexible space, doesn't feel too big.
http://www.bangor.ac.uk/itservices/av/lecturerooms/lectureroom?roomid=46

And Main Arts OSCRB: Just the right size.
http://www.bangor.ac.uk/itservices/av/lecturerooms/lectureroom?roomid=17

.. S-6 is better for parking and refreshments space. OSCRB though has a 70" LCD TV rather than a projector. Space for refreshments in OSCRB isn't as good.

**Comment by robshep** [comment]
Let's try S-6 I think.  

( i'm on 3096 until 17:30 :) )

**Comment by carwyn** [comment]
Confrimed that S-6 (aka 206) is free and reserved the booking, it will be final tomorrow when Donna is back (the person that can "make it so"). Donna is on ext 2752.

**Comment by carwyn** [comment]
Moved to here Small Lecture Theatre

http://www.bangor.ac.uk/itservices/av/lecturerooms/lectureroom?roomid=88

Need to check where the refreshments are going and where to put them. Will pop by the venue tomorrow and check @robshep

**Comment by carwyn** [comment]
We have a refreshments issue #7
