### ISSUE TITLE
Coding Week Event

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#69]
#NationalCodingWeek is Sept 18th onwards. The start of this is the same time as the Digital Festival in Cardiff.

https://codingweek.org/

**Comment by tamslinn** [comment]
Maybe good time for a scratch event targeted at complete beginners? I'd be happy to lead if you think people would be interested? Not sure how we'd advertise to reach people

**Comment by carwyn** [comment]
Chester Devs have been invited to Story House in Chester which we could help out at as well if there's interest.

**Comment by tamslinn** [comment]
I'd be more interested in local events tbh. 
What do you think about scratch in bethesda library? Who should I contact, would it be partneriaeth ogwen now?

**Comment by carwyn** [comment]
By September it may well be. Either Neuadd Ogwen or Cefnfaes would be options too. Library may be a bit small :)
