### ISSUE TITLE
Refreshments for Event 1 (December 2015)

### ISSUE THREAD

**Issue by carwyn** [NorthWalesTech/NorthWalesTech#7]
Mince pies, tea, coffee, biscuits?

**Comment by carwyn** [comment]
Is bara brith Christmassy?

**Comment by davehun** [comment]
On 3 Nov 2015, at 12:01, Carwyn Edwards <notifications@github.com> wrote:
> 
> Is bara brith Christmassy?
> 
Yes

**Comment by carwyn** [comment]
The University conference office can provide refreshments, they even have a Christmas Menu that has Mince Pies:

http://www.bangor.ac.uk/conference_office/menus.php.en

**Comment by robshep** [comment]
Cool.  I reckon we can just ask Sian to organise this for us.  
Our only requirement is mince pies and some tea & coffee I think.

I'll point her at this ticket.

**Comment by carwyn** [comment]
Booked this one http://www.bangor.ac.uk/itservices/av/lecturerooms/lectureroom?roomid=46

Note that someone has the room 5pm to 6pm.

It's plenty big enough to have the refreshments in the room at the back/side. I'll go and scope it out later today if I can to see what the surrounding area is like.

I've phoned the conference office for details on how to order food:

* If the food is delivered after 6pm there's a £20 surcharge (we can probably get it delivered just before 6pm).
* If an external company is paying there's 20% VAT to add to the prices.
* When an external company is paying they need the usual contact details and purchase order number to send the invoice to.

**Comment by carwyn** [comment]
Moved to here Small Lecture Theatre

http://www.bangor.ac.uk/itservices/av/lecturerooms/lectureroom?roomid=88

Need to check where the refreshments are going and where to put them. Will pop by the venue tomorrow and check @robshep

**Comment by carwyn** [comment]
Arrived as planned.
